### ISSUE TITLE
Steps to conduct RNA-seq data analysis in R

### ISSUE THREAD

**Issue by zaarzardad** [griffithlab/rnaseq_tutorial#18]
What are the steps to do RNA-seq data analysis in R? I need to do it using any standard R package (s). Could anybody suggest me the steps with R code?

**Comment by ahwagner** [comment]
Hey @zaarzardad. Is there a specific step you need help with? Our wiki (https://github.com/griffithlab/rnaseq_tutorial/wiki) has an extensive tutorial on running each step of a typical RNA-seq analysis workflow. Many of the steps in this workflow are in R, but some require stand-alone software packages. If you haven't yet, check out the wiki, and let us know if anything is unclear!

**Comment by zaarzardad** [comment]
I want to get numbers from .fasta file to run randomForest ensemble.

**Comment by zaarzardad** [comment]
I want to get numbers from .fasta file to run randomForest ensemble.

**Comment by ahwagner** [comment]
@zaarzardad, RNA-seq data are complex, and there are multiple outputs that you may be interested in for downstream machine learning. If you're looking to get started from RNA-seq .fasta files, step 1 is to align the sequences in those files to a reference genome. I strongly recommend that you work your way through the tutorial [in the wiki](https://github.com/griffithlab/rnaseq_tutorial/wiki) to get a sense of what RNA-seq analysis entails, and so that you can better understand the various outputs for your downstream analysis.

**Comment by zaarzardad** [comment]
Thank you very much!
I will do some reading
